In [2]:
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
import xarray as xr
import pickle
import os
import datetime
from datetime import timezone
import metpy.calc as mpcalc
from metpy.cbook import get_test_data
from metpy.plots import add_metpy_logo, SkewT
from metpy.units import units
from scipy.constants import convert_temperature
from MesoPy import Meso

In [6]:
datafile1 = '../../Data/WRCC_RAWS/Santa_Rosa_CSRS_1.txt'
data1 = pd.read_csv(datafile1,skiprows=4,delim_whitespace=True,)
cols = ['Date','Time','Precip','Spd','Dir','Temp','RH','MaxDir','MaxSpd']
data1.columns = cols
data1.sort_values(by='MaxSpd',ascending=False,inplace=True)
data1.head(20)

,Date,Time,Precip,Spd,Dir,Temp,RH,MaxDir,MaxSpd
81211,2/23/01,20:00,317.200,0.0000,334.0,6.667,83,356,81.36
52972,11/18/97,12:00,153.200,0.0000,162.0,12.220,100,157,75.10
80536,1/26/01,15:00,205.700,0.0000,306.0,7.222,93,354,71.53
52970,11/18/97,10:00,153.200,0.0000,169.0,10.560,100,173,69.74
3374,8/7/91,2:00,34.540,0.0000,179.0,14.440,100,193,65.71
5419,12/6/91,2:00,51.560,0.8941,24.0,6.111,100,299,54.09
11129,11/2/92,14:00,16.000,4.4700,247.0,23.330,74,260,48.73
81217,2/24/01,2:00,318.300,0.0000,255.0,6.111,90,246,45.60
80532,1/26/01,11:00,204.200,0.0000,251.0,7.778,99,265,44.26
6214,2/6/92,8:00,138.200,-9999.0000,30.0,-6.666,-9999,30,40.23
5881,1/10/92,20:00,116.100,0.8941,359.0,8.333,100,35,39.34
81215,2/24/01,0:00,317.200,0.0000,254.0,6.667,89,246,35.32
1054,4/26/91,22:00,34.540,1.7880,307.0,11.110,82,313,32.19
52969,11/18/97,9:00,153.200,2.6820,158.0,9.444,100,181,31.74
8621,6/24/92,2:00,1.016,-9999.0000,82.0,21.110,1,62,31.29
96889,12/14/02,15:00,277.600,17.8800,10.0,11.110,100,15,30.40
225303,10/9/17,4:00,0.000,3.5760,218.0,21.110,12,74,30.40
96013,11/7/02,21:00,62.230,4.0230,298.0,15.000,100,14,27.72
225302,10/9/17,3:00,0.000,11.6200,80.0,32.780,7,95,27.27
90044,3/1/02,1:00,546.400,12.0700,213.0,11.110,19,234,27.27

gust ratio greater than 50